services:
  localstack:
    image: localstack/localstack:3.5
    container_name: rate-limiter-localstack
    environment:
      - SERVICES=dynamodb,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - PERSISTENCE=1
    ports:
      - '4566:4566'
      - '8055:8080'
    volumes:
      - './src/test/resources/localstack/scripts:/etc/localstack/init/ready.d'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - proxy_default

  mockserver:
    image: wiremock/wiremock:2.32.0
    ports:
      - '3055:8080'
    volumes:
      - './src/test/resources/mocks:/home/wiremock'
    networks:
      - proxy_default

networks:
  proxy_default:
    name: proxy_default
