micronaut:
  jms:
    sqs:
      enabled: true

proxy:
  host:
    scheme: http
    name: mockserver
    port: 3055

aws:
  region: us-east-1
  accessKeyId: aws-local-key
  secretKey: aws-local-secret-key
  services:
    dynamo:
      endpoint-override: http://localstack:4566
    sqs:
      endpoint-override: http://localstack:4566
  dynamo:
    endpoint: http://localstack:4566
  sqs:
    endpoint: http://localstack:4566

queues:
  scheduled-messages:
    name: local-scheduled-messages
  processed-messages:
    name: local-processed-messages

rate-limiter:
  enabled: true
  max-requests: 1
  frequency-amount: 1
  frequency-unit: SECONDS
  table-name: local-table
  bucket-name: local-bucket
  shards: 1
